### ISSUE TITLE
https://esp-rs.github.io/std-training/02_2_software.html

### ISSUE THREAD

**Issue by maayanhaimdulberg** [esp-rs/book#123]
Please add to [02_2_software.html](https://esp-rs.github.io/std-training/02_2_software.html) these three packages.
Without them installing espflash doesn't work with WSL:

sudo apt install pkg-config libudev-dev make

Although it is mentioned in the "Troubleshooting area" (apt-get update \ && apt-get install -y vim nano git curl gcc ninja-build cmake libudev-dev python3 python3-pip libusb-1.0-0 libssl-dev \ pkg-config libtinfo5) it is still better to mention it a line before "cargo install cargo-espflash espflash ldproxy"

**Comment by SergioGasquez** [comment]
Hi thanks for opening the issue! Just created https://github.com/esp-rs/std-training/pull/211 and https://github.com/esp-rs/book/pull/124 to improve this.
