### ISSUE TITLE
Add pointers to further guidance

### ISSUE THREAD

**Issue by csgordon** [esp-rs/book#140]
It would be very useful to have a pointer in the book as to where to look for further information, especially if things simply don't work. For example, I've followed the instructions in Chapter 3 (installing Rust, nightly, espup (both the cargo install command and ```espup install```), and sourcing the resulting environment file), and when I build and run the project I get something that's really not covered in the troubleshooting section at all:
```
$ cargo run                                                                                           1 ↵  10059  13:43:09
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `espflash flash --monitor target/riscv32imac-unknown-none-elf/debug/exp3`
[2024-01-31T18:43:17Z INFO ] Detected 6 serial ports
[2024-01-31T18:43:17Z INFO ] Ports which match a known common dev board are highlighted
[2024-01-31T18:43:17Z INFO ] Please select a port
✔ Remember this serial port for future use? · no
[2024-01-31T18:43:19Z INFO ] Serial port: '/dev/cu.usbmodem141401'
[2024-01-31T18:43:19Z INFO ] Connecting...
[2024-01-31T18:43:20Z INFO ] Using flash stub
Chip type:         esp32c6 (revision v0.0)
Crystal frequency: 40MHz
Flash size:        8MB
Features:          WiFi 6, BT 5
MAC address:       40:4c:ca:4e:6a:28
App/part. size:    202,480/8,323,072 bytes, 2.43%
[00:00:00] [========================================]      13/13      0x0
[00:00:00] [========================================]       1/1       0x8000
[00:00:01] [========================================]      79/79      0x10000                                                                                                      [2024-01-31T18:43:21Z INFO ] Flashing has completed!
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x15 (USB_UART_HPSYS),boot:0x4 (DOWNLOAD(USB/UART0/SDIO_FEI_FEO))
Saved PC:0x408007fe
0x408007fe - core::option::Option<T>::unwrap
    at /Users/<user>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:929
waiting for download
```
and it just waits there.

I'm not expecting to get help on this error here in this issue tracker specifically. I wouldn't mind it of course, but mostly I'd just expect just a pointer to the right place to ask, and I think wherever you point me for this issue should probably be mentioned in the book in the troubleshooting section.

**Comment by SergioGasquez** [comment]
Hi! The best place to ask this kind of thing is our [Matrix channel.](https://matrix.to/#/#esp-rs:matrix.org), I'll create a PR adding this channel in the book, as I thought it was there but just realized it isn't.

Now, regarding your issue, it looks like you flash the chip properly (although, I don't see the `Flashing has completed!` message which should be printed before opening the serial monitor) but you are entering download mode, see [esp-idf docs regarding boot modes](https://docs.espressif.com/projects/esptool/en/latest/esp32c6/advanced-topics/boot-mode-selection.html#boot-mode-message). Are you using the GPIO8 and GPIO9?
