### ISSUE TITLE
Clarify std vs no-std

### ISSUE THREAD

**Issue by Timmmm** [esp-rs/book#148]
The book currently says:

>[When You Might Want to Use the Core Library (no_std)](https://docs.esp-rs.org/book/overview/using-the-core-library.html#when-you-might-want-to-use-the-core-library-no_std)
> 1. Small memory footprint: If your embedded system has limited resources and needs to have a small memory footprint, you will likely want to use bare-metal because std features add a significant amount of final binary size and compilation time.
> 2. Direct hardware control: If your embedded system requires more direct control over the hardware, such as low-level device drivers or access to specialized hardware features you will likely want to use bare-metal because std adds abstractions that can make it harder to interact directly with the hardware.
> 3. Real-time constraints or time-critical applications: If your embedded system requires real-time performance or low-latency response times because std can introduce unpredictable delays and overhead that can affect real-time performance.
> 4. Custom requirements: bare-metal allows more customization and fine-grained control over the behavior of an application, which can be useful in specialized or non-standard environments.

Are these really true?

1. As I understand it, esp32-rs uses `build-std` which (when using LTO) should allow unused code to be eliminated (tbf I haven't tested this).
2. Low level device drivers can surely work fine with `std` - any abstractions it adds (I guess you're thinking stuff like filesystem access?) are surely optional?
3. I guess this is talking about multithreading? But is there really any overhead if you never spawn more than one thread?
4. Seems pretty nebulous?

I'm sure there are reasons to use `no_std` but these descriptions didn't really convince me. More specifics would be great here!

It would also be great if there was a section on which parts of `std` are implemented. Seems like threads are? Presumably `std::fs` isn't, etc.

**Comment by MabezDev** [comment]
1 & 3 are definitely true, you simply have more control over the system when building from the ground up with no_std. That isn't to say you can't achieve similar things with std. The others are generally true, I agree a bit vague, but you have to remember that this book is targeting beginners as well as advanced users, if we get bogged down in the details too early people will get lost. One day I'm sure we'll write a esp-nomicon with all the gritty details :D.

> It would also be great if there was a section on which parts of std are implemented. Seems like threads are? Presumably, std::fs isn't, etc.

You're right! This would be helpful. Fortunately, it's easier to list what _isn't_ supported. This is just one module, `process`. Everything else in std works :).

**Comment by Timmmm** [comment]
> Everything else in std works :)

Oh wow that is cool, and surprising! How do you tell `std::fs` how to access the filesystem?

**Comment by MabezDev** [comment]
Sorry this dropped of my radar. When you want to use some file subsystem, whether that's an sd card or FLASH (spiffs) filesystem, you need to mount it by calling some C APIs, after that everything in `std::fs` just works.

I have a very very old demo here: https://github.com/MabezDev/esp-fs-test-suite/blob/1f000b374fa182e76d33bb570cbba280eea0c0a8/src/main.rs#L58-L65 which should give you the general gist.

If you have more questions feel free to join our matrix channel and ask there, for now I'll close this :).
