### ISSUE TITLE
Debugging chapter showing probe-rs as supporting the esp32s3 despite this seemingly not being the case ?

### ISSUE THREAD

**Issue by mindoodoo** [esp-rs/book#164]
Hi,

First of all thanks for the great ressource. I am currently working on getting the built in JTAG interface of the ESP32S3 to work using vscode. Going through the book, it seems like [Chapter 5.3 - Debugging](https://docs.esp-rs.org/book/tooling/debugging/index.html) indicates the ESP32S3 is supported by probe-rs, despite the next sub chapter [Chapter 5.3.1 - probe-rs](https://docs.esp-rs.org/book/tooling/debugging/probe-rs.html) stating :

> There is support for ARM & RISC-V architectures [...]

So to my understanding no extensa support.

The [tracking issue](https://github.com/probe-rs/probe-rs/issues/2001) for extensa support on the probe-rs repository seems to indicate it has not been completed yet, although I have not checked if some of it has been merged.

I am not using probe-rs on my side, however this did seem a little unclear and thought it best to point out :)

**Comment by SergioGasquez** [comment]
Thanks for the issue! probe-rs has been improving the support on Xtensa devices a lot lately, debugging support needs to be improved in Xtensa devices but you can flash all the ESP32 variants with probe-rs at the moment.
