### ISSUE TITLE
Mention that `xtensa-esp32*-{none-elf,espidf}` targets are stable as of Rust 1.81

### ISSUE THREAD

**Issue by flippette** [esp-rs/book#165]
This was mentioned in the GitHub release notes, will this make working with Xtensa ESP32 easier?

**Comment by MabezDev** [comment]
This is by design, the LLVM used by upstream rust does not have enough commits for it to be usable for development (yet). Until it is, we don't want users to get confused so we're omitting talking about it in the book. For now, targeting the Xtensa chips still requires the esp-rs/rust toolchain.
