### ISSUE TITLE
Mermaid graph diagram not rendering

### ISSUE THREAD

**Issue by swanandx** [esp-rs/book#57]
In overview section, there is a [mermaid graph](https://esp-rs.github.io/book/overview/using-the-standard-library.html#relevant-esp-rs-crates) which isn't being rendered on live book.

![image](https://user-images.githubusercontent.com/73115739/210077640-733dbcd4-96bb-4557-a51f-69460bd935be.png)

This should have rendered to something like this:
```mermaid
graph TD;
    esp-idf-hal --> esp-idf-sys & embedded-svc
    esp-idf-svc --> esp-idf-sys & esp-idf-hal & embedded-svc
```

If we run `mdbook serve` locally, the graph gets rendered correctly, this issue is only when it's live on website.

**Comment by jessebraham** [comment]
The diagram is visible for me at least using Firefox on macOS, even when clearing the cache and refreshing the page.

Out of curiosity, which browser/OS are you running?

**Comment by SergioGasquez** [comment]
It's weird as yesterday it was not working for me either but now it works fine. I've tried both Chrome and Brave on MacOs,

**Comment by swanandx** [comment]
I tested on Chrome on Android and Brave on windows. And as you can see in screenshot, it wasn't working at the time of reporting it, but as of now it is working! 😄

**Comment by swanandx** [comment]
> It's weird as yesterday it was not working for me either but now it works fine. I've tried both Chrome and Brave on MacOs,
> 

I wonder what's causing it and how it got fixed automatically 🤔. If it had something to do with mermaid.js, their live demo and playground was working just fine.

**Comment by jessebraham** [comment]
Yeah, not sure. Obviously something funky was going on 😁 

The diagram is still visible for me so I'm going to close this issue, but if you have any other problems please feel free to reopen it.
