### ISSUE TITLE
Tracking the overhaul and re-organization of the book

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/book#59]
Due to a number of factors the book is not currently in the best shape. Due to the nature of organic growth things are not necessarily structured how they should be, and information is spread out all over the place.

In general, in addition to the structural changes listed below, the intent of this effort is to improve the quality of text and remove anything which may cause confusion and/or lie beyond the scope of this book. We can relegate to other documents more than we currently are, for example.

Based on a meeting between @SergioGasquez and myself:

- [x] 1. Introduction #61
  - Why should I use Rust and/or ESP devices?
  - ~~Make it clear that Espressif is involved in the project~~
- [x] 2. Ecosystem Overview #75 
  - What are the different approaches? (`std`, `no_std`)
  - Why should you use one or the other?
  - Combine chip support tables into one
  - Additional sub-chapters or appendices detailing each approach
- [x] 3. #63 - #62 - #74
  - Defer to the tooling's documentation when possible
  - NOT going to document installing Rust
  - NOT going to document install `ldproxy`
  - Move troubleshooting to an Appendix (or something)
- [x] 4. Writing an Application - #81
  - At the very least both `std` and `no_std` should have the same steps in the tutorial
  - We will need to decide how to structure all this
- [x] 5. Tooling - #81
  - For editors, only discuss using VS Code and Rust Analyzer
  - Get rid of the `espmonitor` chapter
  - This whole chapter just needs general improvement (especially debugging)
- [x] 6. Appendix A - Troubleshooting  - https://github.com/esp-rs/book/pull/62/

If you have any questions, concerns, or feedback about these changes please leave a comment below.

**Comment by jessebraham** [comment]
I'm going to begin at... the beginning. Working on the _Introduction_ chapter.

**Comment by SergioGasquez** [comment]
I'll probably close https://github.com/esp-rs/book/pull/50 but, it can be used as a reference for the `espflash` section of chapter 5

**Comment by SergioGasquez** [comment]
I am working on updating the Tooling and Writing Your Own Application chapters

**Comment by SergioGasquez** [comment]
All the content of the chapters are now updated, we well now start working on having a consistent format across the whole book, update the chapter titles and applying the guidelines.
