### ISSUE TITLE
Add troubleshooting step for "invalid toolchain name: 'esp'"

### ISSUE THREAD

**Issue by jayv** [esp-rs/book#78]
I've run into this message on `ubuntu` from running `rustup show` or `cargo build` after doing all the installation steps for ESP via `espup` and trying to build a new project based on `esp-template`
> invalid toolchain name: 'esp'

This was caused by having `rustup` installed via `snap`, removing that and reinstalling `rustup` via the normal shell scripts resolved the issue. 

This should be added to troubleshooting, it would have saved me an hour or more. Snap is really the worst :(

**Comment by SergioGasquez** [comment]
We added a warning note about potential issues when installing rust from package managers, see https://esp-rs.github.io/book/installation/index.html#install-rust. This should avoid issues like your in the future!

I'd close the issue, if you think the warning is not sufficient or can be improved in any way, feel free to reopen it and suggest.
