### ISSUE TITLE
winpty needed with cargo generate command

### ISSUE THREAD

**Issue by dbboyd17** [esp-rs/book#87]
On a windows system, without 'winpty' running the cargo generate command would result  in Error: Incorrect function. (os error 1).

After a bit of searching, I found than preceding the command with winpty made everything worked.

Tripped this newbie up good'n'proper!

**Comment by SergioGasquez** [comment]
Which version of `cargo-generate` do you have? And which template have you tried to use? IIRC, I've generated projects without installing `winpty` in Windows

**Comment by dbboyd17** [comment]
cargo generate 0.18.2

The template was https://github.com/esp-rs/esp-idf-template

 

The issue was only that it might be necessary to use winpty – it worked for me and got me over the initial hump of creating a project. More of a documentation suggestion such as a note

 

Rgds, Bruce.
